config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :brand_partners do 
    resources :items
    resources :benefits
  end
  resources :brand_categories 
  resources :kings_yangon_users do 
    collection do 
      get 'sign_up', to: "kings_yangon_users#sign_up"
      post 'sign_in', to: "kings_yangon_users#sign_in"
      get 'sign_in_page', to: "kings_yangon_users#sign_in_page"
      delete 'log_out', to: "kings_yangon_users#log_out"
    end
  end

  resources :page, only: [] do 
    collection do 
      get 'landing', to: 'page#landing'
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      post '/create', to: 'users#create'
    end
  end
  # resources :users, only: [:index, :show]
  resources :contacts, except: [:new, :create]

  resources :blogs do 
    collection do 
      get '/filter_by_date', to: "blogs#filter_by_date"
    end
  end

  resources :categories
  resources :testimonials

  authenticated :user, ->(user) {user.management?} do
    root to: 'brand_categories#index', as: :management_root
  end

  authenticated :user do
    root to: 'blogs#index', as: :authenticated_root
  end

  authenticated :kings_yangon_user do 
    root to: 'page#landing', as: :landing_page
  end

  unauthenticated do
    devise_scope :user do
      root to: 'page#welcome'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :blogs, only: [:index, :show] do 
        member do 
          get 'blogs_filter_category', to: 'blogs#blogs_filter_category'
          post :increment_view_count
        end
      end
      resources :contacts
    end
  end
end

app/models/brand_partner.rb
class BrandPartner < ApplicationRecord
  paginates_per 4 
  
  belongs_to :brand_category
  has_one_attached :image
  has_many :items, dependent: :destroy
  has_many :benefits, dependent: :destroy
  accepts_nested_attributes_for :benefits, allow_destroy: true

  validates :name, presence: true, length: { maximum: 200 }
  validates :brand_category, presence: true
  # validates :image, attached: true, content_type: { 
  #   in: ['image/png', 'image/jpg', 'image/jpeg'],
  #   message: 'must be a PNG or JPG image'
  # }, on: :update 
end

app/controllers/brand_partners_controller.rb
class BrandPartnersController < ApplicationController
  load_and_authorize_resource
  before_action :set_brand_partner, only: %i[ show edit update destroy ]
  # before_action :check_management_access
  # GET /brand_partners or /brand_partners.json
  def index 
      if params[:query]
       @brand_partners = BrandPartner.where("LOWER(name) LIKE ?", "%#{params[:query]}%").page(params[:page]).per(4)
       return
      end
       if params[:brand_category_id] == "all" || params[:brand_category_id].blank?
        @brand_partners = BrandPartner.includes(:brand_category).order(:name).page(params[:page]).per(4)
      else
        @brand_category = BrandCategory.find(params[:brand_category_id])
        @brand_partners = @brand_category.brand_partners.order(:name).page(params[:page]).per(4)
      end
  end

  # GET /brand_partners/1 or /brand_partners/1.json
  def show
    @items = @brand_partner.items
    @brand_partner
  end

  # GET /brand_partners/new
  def new
    @brand_partner = BrandPartner.new
    @brand_partner.benefits.build
  end

  # GET /brand_partners/1/edit
  def edit
    @brand_partner.benefits.build if @brand_partner.benefits.empty?
  end

  # POST /brand_partners or /brand_partners.json
  def create
    @brand_partner = BrandPartner.new(brand_partner_params)

    respond_to do |format|
      if @brand_partner.save
        format.html { redirect_to brand_partners_path, notice: "Brand partner was successfully created." }
        format.json { render :show, status: :created, location: @brand_partner }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brand_partners/1 or /brand_partners/1.json
  def update
    respond_to do |format|
      if @brand_partner.update(brand_partner_params)
        format.html { redirect_to  brand_partners_path, notice: "Brand partner was successfully updated." }
        format.json { render :show, status: :ok, location: @brand_partner }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand_partner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brand_partners/1 or /brand_partners/1.json
  def destroy
    @brand_partner.destroy!

    respond_to do |format|
      format.html { redirect_to brand_partners_url, notice: "Brand partner was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand_partner
      @brand_partner = BrandPartner.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_partner_params
      params.require(:brand_partner).permit(:name, :brand_category_id, :image, benefits_attributes: [:id, :content, :remark, :_destroy])
    end
end

app/helpers/brand_partners_helper.rb
module BrandPartnersHelper
end

app/views/brand_partners/_benefit_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%#= f.label :content, class: 'form-label mt-3' %>
  <div class="d-flex align-items-center justify-content-between gap-3 my-2 ">
    <%= f.text_field :content, class: 'form-control' %>

    <button type="button" data-action="nested-form#remove">
        <i class="bi bi-x-circle" style="font-size: 20px;"></i>
    </button>
  </div>
  <%= f.hidden_field :_destroy %>
</div>

<% if f.object.errors.any? %>
  <small class="text-danger d-block"><%=  f.object.errors.full_messages.join(', ')%></small>
<% end %>

app/views/brand_partners/_brand_partner.html.erb
<div class="detail-container px-5">
  <%= render partial: 'shared/detail/header', locals: {title: 'Brand Partners'} %>
  <%= render  'shared/detail/content_container' do %>
      <%= render 'shared/detail/content_body_container' do %>
        <p class="row" >
              <% if @brand_partner.image.present? %>
                <small class="col-lg-4">Brand image</small>
                <small class="col-lg-8 fw-bold">
                  <%= image_tag @brand_partner.image, style: 'width: 100px; height: 100px; object-fit: cover;', alt: 'banner' %>
              </small>
              <% end %>
        </p>

        <p class="row" >
          <small class="col-lg-4">Name</small>
          <small class="col-lg-8 fw-bold"><%= @brand_partner.name %></small>
        </p>

        <p class="row">
          <small class="col-lg-4">Category</small>
          <small class="col-lg-8 fw-bold"><%= @brand_partner.brand_category.name %></small>
        </p>

          <% unless  @brand_partner.benefits.empty? %>
            <p class="row">
                <small class="col-lg-4">Benefits</small>
                    <small class=" col-lg-8 list-group">
                      <% @brand_partner.benefits.each do |benefit| %>
                        <small class=" fw-bold list-group-item"><%= benefit.content %></small>
                      <% end %>
                    </small>
            </p>
          <% end %>

        <p class="row">
          <small class="col-lg-4">Created At</small>
          <small class="col-lg-8 fw-bold"><%= @brand_partner.created_at.strftime('%Y-%m-%d') %></small>
        </p>

        <p class="row">
          <small class="col-lg-4">Updated At</small>
          <small class="col-lg-8 fw-bold"><%= @brand_partner.updated_at.strftime('%Y-%m-%d') %></small>
        </p>
      <% end %>
    <%= render partial: 'shared/detail/footer', locals: {return_path: brand_partners_path , edit_path: edit_brand_partner_path(@brand_partner) ,
     destroy_path: brand_partner_path(@brand_partner), record: @brand_partner.name} %>
  <% end %>
</div>

app/views/brand_partners/_form.html.erb
<%= render 'shared/back_button' %>
<%= render 'layouts/auth_layout' do %>

  <% if @brand_partner.persisted? %>
    <h2 class="form-title">Update Brand Partner</h2>
  <% else %>
    <h2 class="form-title">Create Brand Partner</h2>
  <% end %>
  <div class="form-container">
      <%= form_with(model: brand_partner, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } ) do |form| %>
      <div class="mb-4">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :name, record: brand_partner} %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-4">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :brand_category, record: brand_partner} %>
        <%= form.select :brand_category_id, BrandCategory.order(:name).map { |brand_category| [brand_category.name, brand_category.id] }, {prompt: "Select Category"}, {class: 'form-select'} %>
      </div>

      <div class="mb-4">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :image, record: brand_partner} %>
        <% if brand_partner.image.attached? && brand_partner.image.persisted? %>
          <%= form.hidden_field :image, value: brand_partner.image.signed_id %>
        <% end %>

        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="mb-4" >
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :benefits, record: brand_partner} %>
          <template data-nested-form-target="template">
            <%= form.fields_for :benefits, Benefit.new, child_index: 'NEW_RECORD' do |benefit_form| %>
              <%= render "benefit_form", f: benefit_form %>
            <% end %>
          </template>

            <%= form.fields_for :benefits do |benefit_form| %>
              <%= render 'benefit_form', f: benefit_form %>
            <% end %>

        <div data-nested-form-target="target"></div>  

        <div class="d-flex align-items-center justify-content-end mt-2">
            <button type="button" data-action="nested-form#add">
              <i class="bi bi-plus-circle" style="font-size: 20px;"></i>
            </button>
        </div>

      </div>

      <div class="mt-3">
          <% unless @brand_partner.persisted?%>
              <%= form.submit "Create", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% else %>
              <%= form.submit "Update", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% end %>      
      </div>
    <% end %>
  </div>
<% end %>

app/views/brand_partners/_table.html.erb
<table class="table">
  <thead class="bg-light">
    <tr>
      <th class="fw-bold">Name</th>
      <th class="fw-bold">Category</th>
      <th class="fw-bold">Benefits</th>
      <th class="fw-bold">Actions</th>
    </tr>
  </thead>
    <tbody>
        <% if brand_partners.empty? %>
            <%= render 'shared/no_data_table' %>
        <% else %>
        <% brand_partners&.each do |brand_partner| %>
                <tr>
                    <td>
                        <div class="d-flex align-items-center">
                        <% if brand_partner.image.present? %>
                            <%= image_tag brand_partner.image, alt: 'brand_partner', width: 45, height: 45, class: 'rounded-circle'%>
                        <% end %>
                        <div class="ms-3">
                            <p class="fw-bold mb-1"><%= brand_partner.name %></p>
                        </div>
                        </div>
                    </td>
                    <td>
                        <p class="fw-normal mb-1"><%= brand_partner.brand_category.name %></p>
                    </td>
                    <td>
                        <p class="fw-normal mb-1"><%= brand_partner.benefits.count %></p>
                    </td>
                    <td class="">
                        <%= link_to brand_partner_path(brand_partner), data: {turbo: false} do  %>
                            <i class="bi bi-eye-fill" style="font-size: 1.2rem"></i>
                        <% end %>

                    <% if current_user.management? %>
                            <%= link_to 'Edit',  edit_brand_partner_path(id: brand_partner.id), data: {turbo: false}, class: 'btn btn-link btn-sm btn-rounded' %>
                            <%#= link_to 'Create', new_user_path, class: ' btn btn-link btn-sm btn-rouned' %>
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" id="brandCategoryModalLabel<%= brand_partner.id %>" data-bs-target="#brandCategoryModal<%= brand_partner.id %>">
                                Delete
                            </button>
                            <!-- Modal -->
                        <div class="modal fade" id="brandCategoryModal<%= brand_partner.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="brandCategoryModalLabel<%= brand_partner.id %>" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Delete <%= brand_partner.name %></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body text-center fw-semibold">
                                    <small class="border border-warning rounded p-4 d-flex align-items-center" style="background-color: #FFF8DD">
                                        <i class="bi bi-exclamation-circle me-2 text-warning fs-5"></i>
                                        <p class="mb-0">Are you sure you want to delete <%= brand_partner.name %> ?</p>
                                    </small>
                                </div>
                                <div class="modal-footer">
                                    <%= button_to "Delete", brand_partner_path(brand_partner), { class: 'btn btn-danger', method: :delete } %>
                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                </div>
                                </div>
                            </div>
                        </div>
                    <% end %>

                    </td>
                </tr>
        <% end %>
        <% end %>

    </tbody>
</table>
<%= render 'shared/paginate_footer', locals: {items: brand_partners} %>




app/views/brand_partners/edit.html.erb
<%= render "form", brand_partner: @brand_partner %>

app/views/brand_partners/index.html.erb
<%= render 'shared/back_button' %>
<%= render 'shared/create_button', locals: {link: new_brand_partner_path, }%>

<div id="brand_partners" >
  <div class="d-flex align-items-center gap-4">
      <div class="">
        <%= render 'shared/search_form', locals: {link: brand_partners_path, title: 'Brand Partners', current_data: @brand_partners } %>
      </div>
      <div class="">
        <h6>Filter By Category</h6>
        <%= form_with url: brand_partners_path, method: :get, remote: true do |f| %>
        <%= f.collection_select :brand_category_id, 
                [["All", "all"]] + BrandCategory.order(:name).pluck(:name, :id), 
                :last, :first, 
                { selected: params[:brand_category_id].present? ? params[:brand_category_id] : "all" },
                { class: 'form-select', onchange: 'this.form.submit();' } %>
        <% end %>
      </div>
  </div>


<%= render partial: 'table', locals: { brand_partners: @brand_partners } %>
</div>

app/views/brand_partners/new.html.erb
<%= render "form", brand_partner: @brand_partner %>

app/views/brand_partners/show.html.erb
<%= render @brand_partner %>

<div class="px-5 mt-5">
    <%#= render partial: 'shared/detail/header', locals: {title: 'Items'} %>
    <div class="my-3">
        <%#= render 'shared/create_button', locals: {link: new_brand_partner_item_path(@brand_partner)} %>
    </div>
</div>

<%# unless @items.empty? %>
  <%# <ul class="mt-4 row"> %>
    <%# @items&.each do |item| %>
      <%# render partial: 'items/item', locals: {item: item, brand_partner: @brand_partner} %>
    <%# end %>
  <%# </ul> %>
<%# else %>
  <%#= render 'shared/no_data' %>
<%# end %>