config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :brand_partners do 
    resources :items
    resources :benefits
  end
  resources :brand_categories 
  resources :kings_yangon_users do 
    collection do 
      get 'sign_up', to: "kings_yangon_users#sign_up"
      post 'sign_in', to: "kings_yangon_users#sign_in"
      get 'sign_in_page', to: "kings_yangon_users#sign_in_page"
      delete 'log_out', to: "kings_yangon_users#log_out"
    end
  end

  resources :page, only: [] do 
    collection do 
      get 'landing', to: 'page#landing'
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      post '/create', to: 'users#create'
    end
  end
  # resources :users, only: [:index, :show]
  resources :contacts, except: [:new, :create]

  resources :blogs do 
    collection do 
      get '/filter_by_date', to: "blogs#filter_by_date"
    end
  end

  resources :categories
  resources :testimonials

  authenticated :user, ->(user) {user.management?} do
    root to: 'brand_categories#index', as: :management_root
  end

  authenticated :user do
    root to: 'blogs#index', as: :authenticated_root
  end

  authenticated :kings_yangon_user do 
    root to: 'page#landing', as: :landing_page
  end

  unauthenticated do
    devise_scope :user do
      root to: 'page#welcome'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :blogs, only: [:index, :show] do 
        member do 
          get 'blogs_filter_category', to: 'blogs#blogs_filter_category'
          post :increment_view_count
        end
      end
      resources :contacts
    end
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new()
    if user.admin? 
      can :manage, [Blog, User, Testimonial, Contact, Category]
    elsif user.management? 
      can :manage, [BrandPartner, BrandCategory, Item, KingsYangonUser, Banner]
    else  
      can :read, :all
      can [:sign_in_page, :sign_in, :log_out], KingsYangonUser unless user.admin?
    end 

    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/banner.rb
class Banner < ApplicationRecord
    paginates_per 4 

    has_one_attached :image
    validates :caption, presence: true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :brand_partner

  validates :content, presence: true
  validates :brand_partner, presence: true
  validates :brand_partner_id, presence: true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :category
  has_one_attached :image  
  has_rich_text :content
  
  paginates_per 4 

  validates :content, presence: true  
  validates :category_id, presence: true
  validates :views_count, numericality: { integer: true}
  validates :blog_status, presence: true, inclusion: { in: %w(pending approve deny) }
  validates :delete_flg, inclusion: { in: [true, false] }
  validates :title, presence: true, length: { maximum: 100 }

  enum blog_status: { pending: 0, approve: 1, deny: 2 }

  def increase_view_count
    increment!(:views_count)
  end
  private 

end

app/models/brand_category.rb
class BrandCategory < ApplicationRecord
    paginates_per 4 

    has_many :brand_partners, dependent: :destroy

    validates :name, presence: true, length: {in: 2..30}
    validates :description, presence: true
end

app/models/brand_partner.rb
class BrandPartner < ApplicationRecord
  paginates_per 4 
  
  belongs_to :brand_category
  has_one_attached :image
  has_many :items, dependent: :destroy
  has_many :benefits, dependent: :destroy
  accepts_nested_attributes_for :benefits, allow_destroy: true

  validates :name, presence: true, length: { maximum: 200 }
  validates :brand_category, presence: true
  # validates :image, attached: true, content_type: { 
  #   in: ['image/png', 'image/jpg', 'image/jpeg'],
  #   message: 'must be a PNG or JPG image'
  # }, on: :update 
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :blogs

    paginates_per 4 

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :student_name, :parent_name,  presence: true, length: {maximum: 40}
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :phone_number, presence: true, length: {maximum: 12}, format: { with: /\A\+?[\d\s-]{7,15}\z/, message: "must be a valid phone number" }
    validates :birth_date, presence: true, comparison: {less_than: Date.current}
    validates :gender, presence: true, length: {maximum: 10 }
    validates :nationality, :current_school, :current_year_group, presence: true, length: {maximum: 50 }
    validates :address, presence: true, length: {maximum: 100 }
    validates :message, presence: true, length: { maximum: 500 }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand_partner
  has_many_attached :images

  validates :name, presence: true, length: {maximum: 50}
  validates :price, presence: true, numericality: {allow_float: true}
  validates :discount_percentage, allow_nil: true, numericality: {allow_integer: true}
  validates :brand_partner, presence: true
end

app/models/kings_yangon_user.rb
class KingsYangonUser < ApplicationRecord
    paginates_per 4 

    validates :school_id, uniqueness: true, presence: true, length: { in: 6..30 }
    
    enum user_type: {"student": 0, "teacher": 1, "staff": 2}
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  has_one_attached :image

  paginates_per 4 

  validates :name, presence: true, length: { maximum: 50 }
  validates :speech, presence: true
  validates :current_year_group, presence: true, length: {maximum: 100}
  validates :batch_year, presence: true
  private 
  # def batch_year_cannot_be_two_year_future
  #   if batch_year.present? && batch_year > Date.current.year + 2
  #     errors.add(:batch_year, ' cannot be two years into the future')
  #   end
  # end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: {user: 0, admin: 1, management: 2}  
  paginates_per 4 
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true, length: { in: 3..20 }
  validates :department, presence: true
  validates :title, presence: true
  validates :position, presence: true, length: { in: 4..30 }
  validates :role, allow_blank: true, inclusion: { in: roles.keys }

  def self.create_with_default_password(attr={}) 
    default_password = 'password'
    self.create(attr.merge(password: default_password, password_confirmation: default_password))
  end

  def change_password?
    self.change_password
  end
  private
end

app/helpers/banners_helper.rb
module BannersHelper
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<%# www/app/views/active_storage/blobs/_blob.html.erb %>
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.video? %>
    <video
      controls="false"
      width="100%"
      poster=<%= polymorphic_url(blob.representation(resize_to_limit: [ 1024, 768 ])) %>
    >
      <source src= <%= rails_blob_url(blob) %>, type=<%= blob.content_type %> >
    </video>
  <% elsif blob.audio? %>
    <audio controls="true" width="100%" preload="metadata">
      <source src= <%= rails_blob_url(blob) %>, type=<%= blob.content_type %> >
    </audio>
  <% elsif blob.content_type == 'application/pdf' %>
    <embed src=<%= rails_blob_url(blob) %> width="800" height="500"
           type="application/pdf">
  <% elsif blob.content_type == 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' %>
    <iframe src='https://view.officeapps.live.com/op/embed.aspx?src=<%= rails_blob_url(blob) %>' width='100%' height='500px' frameborder='0'>
    </iframe>
<% elsif blob.representable? %>
    <%#= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
    <figure class="my-2">
      <%= image_tag rails_blob_url(blob), size: '300x300'%>
    </figure>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
    <% end %>
    <span> · </span>
    <%= link_to "Download", rails_blob_path(blob, disposition: "attachment") %>
  </figcaption>
</figure>

app/views/page/landing.html.erb
<%= render 'shared/navbar' %>
<div id='home-section' style="height: 70vh;">
    <%= render partial: 'page/landing/carousel', locals: {banners: @banners} %>
</div>
<%#= render partial: 'page/landing/banner_carousel', locals: {banners: @banners} %>
<section class="partner-section pt-5" style="background-color:#f9fafc;" >
        <h1 class="text-center fw-bold text-black custom-font">Our Partners</h1>
        <ul class="category-container p-4 d-flex gap-4 align-items-center ms-5 mt-4" id="pills-tab" role="tablist">
            <% @brand_categories.each_with_index do |brand_category, index| %>
                <li class="" role="presentation">
                    <button 
                        class="category-text <%= 'active' if index == 0 %>" 
                        id="pills-tab<%= brand_category.id %>" 
                        data-bs-toggle="pill" 
                        data-bs-target="#pills<%= brand_category.id %>" 
                        type="button" 
                        role="tab" 
                        aria-controls="pills<%= brand_category.id %>" 
                        aria-selected="<%= index == 0 %>">
                        <%= brand_category.name %>
                    </button>
                </li>
            <% end %>
        </ul>

        <%# tab content  %>
        <div class="tab-content" id="pills-tabContent">
            <% @brand_categories.each_with_index do |brand_category, index| %>
                <% unless brand_category.brand_partners.empty? %>
                    <div 
                        class="tab-pane fade p-5 75vh <%= 'show active' if index == 0 %>" 
                        style="min-height: 70vh;"
                        id="pills<%= brand_category.id %>" 
                        role="tabpanel" 
                        aria-labelledby="pills-tab<%= brand_category.id %>">
                        <div class=' brand-card-container gap-5 ' >
                        <% brand_category.brand_partners.order(:name).each do |brand_partner| %>
                            <button class="brand-card px-4 py-2" type="button"
                                    data-bs-toggle="modal" data-bs-target="#brandPartnerModal<%= brand_partner.id %>">
                                <%= image_tag brand_partner.image, class: 'brand-image' if brand_partner.image.attached? %>
                                <p class="fw-semibold text-pink mt-2 mb-0"><%= brand_partner.name %></p>
                            </button>
                            <%= render partial: 'shared/modal/modal', locals: {modal_id: "brandPartnerModal#{brand_partner.id}",
                             modal_title: brand_partner.name, category: brand_partner.brand_category.name, benefits: brand_partner.benefits, 
                             image: brand_partner.image } %>
                        <% end %>
                        </div> 
                    </div>    
                <% end %>
            <% end %>
        </div>
</section>
<div id="footer-section">
    <%= render 'page/landing/footer' %>
</div>

app/views/page/welcome.html.erb
<section class="welcome-section">
    <div class="container-fluid welcome-container w-100 vh-100 d-flex flex-column  ">
        <div class="welcome-text-container flex-fill d-flex justify-content-center flex-column align-items-center ">
            <h2 class="text-white custom-font text-center fs-3 fs-md-4 fs-lg-3">Welcome To Kings Yangon</h2>
            <span class="text-white custom-font text-center d-block fs-lg-4">Kings Education For Life </span>
            <div class="sign-in-link-container d-none d-md-flex justify-content-center gap-4 mt-5">
                <%= link_to "Admin", new_user_session_path, class:'welcome-sign-in-btn bg-pink-opacity custom-font' %>
                <%= link_to "Parent", sign_in_page_kings_yangon_users_path, class:'welcome-sign-in-btn border border-white custom-font' %>
            </div>
        </div>
        <div class="sign-in-link-container d-flex d-md-none justify-content-center gap-4 pb-5">
            <%= link_to "Admin", new_user_session_path, class:'welcome-sign-in-btn bg-pink-opacity custom-font' %>
            <%= link_to "Parent", sign_in_page_kings_yangon_users_path, class:'welcome-sign-in-btn border border-white custom-font' %>
        </div>
    </div>
</section>

app/views/shared/_back_button.html.erb
<div class=" container d-flex pe-5 ">
    <%= link_to "<i class='bi bi-arrow-left'></i> Back".html_safe, :back, class: "btn btn-secondary" %>
</div>

app/views/shared/_carousel.html.erb

<!-- Slideshow container -->
<div class="slideshow-container" style="height: 300px; width: 500px">
  <!-- Full-width images with number and caption text -->
  <% (blog.images + blog.videos).each_with_index do |media, index| %>
        <div class="mySlides ">  
            <div class="numbertext"><%= index + 1 %> / <%= blog.images.size + blog.videos.size %></div>
            <% if media.blob.content_type.start_with?('image') %>
                <%= image_tag url_for(media), width: '500', height: '300', alt: 'blog photos' %>
            <% elsif media.blob.content_type.start_with?('video') %>
                <%= video_tag url_for(media), size: '500x300', controls: true, alt: 'blog videos' %>
            <% end %>
        </div>
  <% end %>
  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>
</div>
<br>

<!-- The dots/circles -->
<div style="text-align:center" class="mt-5">
    <% (blog.images + blog.videos).each_with_index do |media, index|%>
        <span class="dot" onclick="currentSlide(<%= index + 1 %>)"></span>
    <% end %>
</div>

<%= javascript_include_tag "carousel" %>

app/views/shared/_create_button.html.erb
<div class=" container justify-content-end d-flex pe-5 ">
    <%= link_to  locals[:link], class:'btn btn-primary' do  %>
        <span class="me-1">Add</span>
         <i class="bi bi-plus-lg"></i>
    <% end %>
</div>

app/views/shared/_filter_date.html.erb

<div class="my-4 d-none" >
    <%= form_with url: filter_by_date_blogs_path, method: :get do |f|  %>
        <div class="d-flex align-items-center flex-wrap column-gap-2">
            <div class="d-flex  column-gap-2">
                <%= f.label :from_date , 'From', class: 'form-label'%>
                <%= f.date_field :from_date, class:' form-control'   %>
            </div>

            <div class="d-flex  column-gap-2">
                <%= f.label :to_date, 'To', class: 'form-label'%>
                <%= f.date_field :to_date, class:' form-control'     %>
            </div>
        </div>
   
            <div class="search-btn-box  my-2">
                 <%= f.submit 'Search', class:'btn btn-primary' %>
            </div>

    <% end %>
</div>

<div class="my-4">
    <%= form_with url: blogs_path,  method: :get do |f| %>
        <div class="d-flex align-items-center gap-3">
            <div>
                <%= f.text_field :daterange, value: params[:daterange], name: 'daterange', data: { controller: 'daterangepicker' }, size: 24, style: 'text-align:center', class: 'pe-auto' %>
            </div>
            <div>
                <%= f.submit 'Search', class:'btn btn-primary' %>
            </div>
        </div>


    <% end %>
</div>

app/views/shared/_form_title.html.erb
  <%# <h5 class="fw-semibold text-center py-3 
  <%= !is_sign_in_page? ? 'border border-1 bg-primary text-white': 'text-primary' %><%#= locals[:title] %>

  <h5 class="form-title"><%= locals[:title]%></h5>

app/views/shared/_label_with_errors.html.erb
<% if record.errors[field_name].any? %>
  <%= form.label field_name, class: 'form-label text-danger' do %>
    <%= record.errors.full_messages_for(field_name).join(", ") %>
  <% end %>
<% else %>
  <%= form.label field_name, class: 'form-label' %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top bg-dark-grey bg-opacity-75 border-0 px-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag 'logo', size: '120x50', class: 'd-inline-block align-text-top'%>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse  justify-content-center" id="navbarNavAltMarkup">
      <div class="navbar-nav d-none">
        <a class="nav-link  text-pink fw-semibold" aria-current="page" href="#home-seciton">Home</a>
        <a class="nav-link text-pink fw-semibold" href="#footer-section">About Us</a>
        <%= button_to 'Log Out', log_out_kings_yangon_users_path, method: :delete , class: 'nav-link text-pink fw-semibold d-md-none'%>
      </div>
    </div>
      <div class="logout-btn-container ms-auto d-none d-md-block">
        <%= button_to 'Log Out', log_out_kings_yangon_users_path, method: :delete , class: '  btn btn-danger px-3 fw-semibold text-white py-1 '%>
      </div>
  </div>
</nav>

app/views/shared/_no_data.html.erb
<section class="d-flex flex-column align-items-center my-4 py-4 justify-content-center w-100 border border-1 ">
    <%= image_tag "empty_icon.jpg",  size: '100x100' %>
    <h6 class="text-muted">There is no data right now </h6>
</section>

app/views/shared/_no_data_table.html.erb
<tr>
    <td colspan="<%= local_assigns[:colspan] || 5 %>">
        <%= render 'shared/no_data' %>
    </td>
</tr>

app/views/shared/_noti.html.erb
<% if flash[:notice]%>
    <div 
        class="alert alert-success transition transform duration-1000 position-absolute
         hidden d-flex align-items-center gap-3" 
         style="max-width: 50%;"
        data-controller="notification"
        data-notification-delay-value="2000"
        data-transition-enter-from="opacity-0 translate-y-6"
        data-transition-enter-to="opacity-100 translate-y-0"
        data-transition-leave-from="opacity-100 translate-y-0"
        data-transition-leave-to="opacity-0 translate-y-6"
       
    >              
        <i class="bi bi-check-circle-fill me-1 text-light-green"></i>
        <strong class="text-black me-5"><%= flash[:notice] %> </strong> 
    <button data-action="notification#hide" class="ms-auto">
        <i class="bi bi-x-circle border-none"></i>
    </button>
    </div>
<% end %>



<% if flash[:alert] %>
    <div 
        class="alert alert-danger  transition transform duration-1000 position-absolute
         hidden "
        data-controller="notification"
        data-notification-delay-value="2000"
        data-transition-enter-from="opacity-0 translate-y-6"
        data-transition-enter-to="opacity-100 translate-y-0"
        data-transition-leave-from="opacity-100 translate-y-0"
        data-transition-leave-to="opacity-0 translate-y-6"
       
    >               
        <i class="bi bi-check-circle-fill me-3 text-light-green"></i>
        <strong class="text-black"><%= flash[:alert] %></strong> 
    <button data-action="notification#hide" class="ms-auto">
        <i class="bi bi-x-circle border-none"></i>
    </button>
    </div>
<% end %>

app/views/shared/_paginate_footer.html.erb
<div class="paginate-box mt-4">
    <%= paginate locals[:items] %>
</div>

app/views/shared/_search_form.html.erb
<div class="my-2">
    <%= render 'shared/total_number', locals: {title: locals[:title] , current_data: locals[:current_data] }%>
    <div class=" d-flex align-items-center ">
        <%= form_with url: locals[:link], method: :get do |form| %>
            <div class="input-group">
                <%= form.text_field :query, class: "form-control", type: "search", placeholder: "Search",  aria: { label: "Search", describedby: "search-addon" } %>
                <%= form.submit "Search", class: 'btn btn-primary'%>
            </div>
        <% end %>
    </div>
</div>

app/views/shared/_stimulus_carousel.html.erb
<!-- Slider main container -->
<div class="swiper w-100">
  <!-- Additional required wrapper -->
  <div class="swiper-wrapper">
    <!-- Slides -->
    <% images&.each do |media| %>
        <div class="swiper-slide ">
            <% if media.blob.content_type.start_with?('image') %>
              <%= image_tag media, class: 'd-block w-100 img-fluid h-100 object-fit-cover', alt: "carousel image"%>
            <% elsif media.blob.content_type.start_with?('video')%>
                <%= video_tag url_for(media), controls: true, class: 'd-block w-100 img-fluid h-100 object-fit-cover', alt: 'blog videos' %>
            <% end %>
        </div> 
    <% end %>
  </div>
  <!-- If we need pagination -->
  <div class="swiper-pagination"></div>

  <!-- If we need navigation buttons -->
  <div class="swiper-button-prev"></div>
  <div class="swiper-button-next"></div>

  <!-- If we need scrollbar -->
  <div class="swiper-scrollbar"></div>
</div>

app/views/shared/_total_number.html.erb
<h6>Total <%= locals[:title] %> - <%= locals[:current_data]&.total_count %></h6>