config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :brand_partners do 
    resources :items
    resources :benefits
  end
  resources :brand_categories 
  resources :kings_yangon_users do 
    collection do 
      get 'sign_up', to: "kings_yangon_users#sign_up"
      post 'sign_in', to: "kings_yangon_users#sign_in"
      get 'sign_in_page', to: "kings_yangon_users#sign_in_page"
      delete 'log_out', to: "kings_yangon_users#log_out"
    end
  end

  resources :page, only: [] do 
    collection do 
      get 'landing', to: 'page#landing'
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      post '/create', to: 'users#create'
    end
  end
  # resources :users, only: [:index, :show]
  resources :contacts, except: [:new, :create]

  resources :blogs do 
    collection do 
      get '/filter_by_date', to: "blogs#filter_by_date"
    end
  end

  resources :categories
  resources :testimonials

  authenticated :user, ->(user) {user.management?} do
    root to: 'brand_categories#index', as: :management_root
  end

  authenticated :user do
    root to: 'blogs#index', as: :authenticated_root
  end

  authenticated :kings_yangon_user do 
    root to: 'page#landing', as: :landing_page
  end

  unauthenticated do
    devise_scope :user do
      root to: 'page#welcome'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :blogs, only: [:index, :show] do 
        member do 
          get 'blogs_filter_category', to: 'blogs#blogs_filter_category'
          post :increment_view_count
        end
      end
      resources :contacts
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :brand_partner
  has_many_attached :images

  validates :name, presence: true, length: {maximum: 50}
  validates :price, presence: true, numericality: {allow_float: true}
  validates :discount_percentage, allow_nil: true, numericality: {allow_integer: true}
  validates :brand_partner, presence: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    # Retrieve all items for a specific brand partner
    @brand_partner = BrandPartner.find(params[:brand_partner_id])
    @items = @brand_partner.items
  end

  def show
    # Retrieve a specific item for a specific brand partner
  end

  def new
    # Create a new item for a specific brand partner
    @brand_partner = BrandPartner.find(params[:brand_partner_id])
    @item = @brand_partner.items.new
  end

  def create
    # Create a new item for a specific brand partner
    @brand_partner = BrandPartner.find(params[:brand_partner_id])
    @item = @brand_partner.items.new(item_params)

    if @item.save
      redirect_to brand_partner_path(@brand_partner), notice: 'Item was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # Edit an existing item for a specific brand partner
  end

  def update
    # Update an existing item for a specific brand partner

    if @item.update(item_params)
      redirect_to brand_partner_path(@brand_partner), notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # Delete an existing item for a specific brand partner
    if @item.destroy
      redirect_to brand_partner_path(@brand_partner), notice: 'Item was successfully destroyed.'
    end
  end

  private

  def set_item
    @brand_partner = BrandPartner.find(params[:brand_partner_id])
    @item = @brand_partner.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :price, :content, :discount_percentage, :brand_partner_id, images: [])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= render 'layouts/auth_layout' do %>
    <% if item.persisted?%>
      <%= render 'shared/form_title', locals:{title: 'UPDATE ITEM' }%>
    <% else %>
        <%= render 'shared/form_title', locals:{title: 'CREATE ITEM' }%>
    <% end %>
  <div class="p-3">
    <%= form_with(model: [@brand_partner, item]) do |form| %>
      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :name, record: item} %>
        <%= form.text_field :name, class:'form-control' %>
      </div>

      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :content, record: item} %>
        <%= form.text_area :content, class: 'form-control' %>
      </div>

      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :price, record: item} %>
        <%= form.text_field :price, class: 'form-control' %>
      </div>

      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :discount_percentage, record: item} %>
        <%= form.text_field :discount_percentage, class: 'form-control' %>
      </div>

      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :brand_partner_id, record: item} %>
        <%= form.select :brand_partner_id, BrandPartner.order(:name).map { |brand_partner| [brand_partner.name, brand_partner.id]}, {prompt: "Select Category"}, {class: 'form-select'}  %>
      </div>

      <div class="mt-3">
        <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :images, record: item} %>
        <% if item.images.attached? %>
          <% item.images.each do |image| %>
            <%= form.hidden_field :images, multiple: true, value:image.signed_id %>
          <% end %>
        <% end %>
        <%= form.file_field :images, multiple: true, class: 'form-control' %>
      </div>

      <div class="mt-3">
          <% unless item.persisted?%>
              <%= form.submit "Create", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% else %>
              <%= form.submit "Update", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% end %>      
      </div>
    <% end %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="item-card col me-3 rounded  overflow-hidden  shadow ">
  <div class='item-carousel-container' >
    <%= render partial: 'shared/stimulus_carousel', locals: {images: item.images} %>
  </div>
  <%# for default carousel  %>


  <%# for default carousel %>
  <div class="item-card-body mt-2 p-3">
    <h4 class="text-capitalize fw-semibold"> <%= item.name %></h6>
    <p class="d-block mb-0 overflow-auto text-break" style="height: 50px">
      <%= item.content %>
    </p>
    <p class="d-block mb-0 mt-3">
      <span><%= item.price unless item.discount_percentage%></span>
      <span><%= calculate_percentage(item.price, item.discount_percentage) if item.discount_percentage %></span>
      <% if item.discount_percentage %>
        <span class="text-secondary"><del class="text-decoration-line-through"><%= item.price %></del></span>
      <% end %>
    </p>
  </div>

  <div class="item-footer p-3 d-flex justify-content-between">
    <%= link_to 'Edit', edit_brand_partner_item_path(@brand_partner, item), class: ' btn btn-secondary' %>
    <%= link_to 'delete', '#', class: 'btn btn-danger', data: { bs_toggle: 'modal', bs_target: "#deleteItemModal#{item.id}" } %>

    <%# delete modal  %>
            <div class="modal fade" id="deleteItemModal<%= item.id %>" tabindex="-1" aria-labelledby="deleteItemModal<%= item.id %>" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="deleteItemModal<%= item.id %>">Delete <%= item.name %></h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body p-4">
                    <%= render partial: 'shared/modal/modal_body', locals: {record: item.name}%>
                </div>
                <div class="modal-footer">
                  <%=  link_to 'Close', '#', class:'btn btn-secondary', data: {bs_dismiss: 'modal'}%>
                  <%= button_to 'Delete', brand_partner_item_path(@brand_partner, item), method: :delete, class: 'btn btn-danger'%>
                </div>
              </div>
            </div>
          </div>
    <%#= button_to 'Delete', brand_partner_item_path(@brand_partner, item), method: :destroy, class: 'btn btn-danger' %>
  </div>
</div>

app/views/items/edit.html.erb
<%= render 'shared/back_button' %>
<%= render "form", item: @item %>

app/views/items/index.html.erb
<h1>Items</h1>

<div id="items">
  <% items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", item %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_item_path %>

app/views/items/new.html.erb
<%= render 'shared/back_button'%>
<%= render "form", item: @item %>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_item_path(@item) %> |
  <%= link_to "Back to items", items_path %>

  <%= button_to "Destroy this item", @item, method: :delete %>
</div>