config/routes.rb
Rails.application.routes.draw do
  resources :banners
  resources :brand_partners do 
    resources :items
    resources :benefits
  end
  resources :brand_categories 
  resources :kings_yangon_users do 
    collection do 
      get 'sign_up', to: "kings_yangon_users#sign_up"
      post 'sign_in', to: "kings_yangon_users#sign_in"
      get 'sign_in_page', to: "kings_yangon_users#sign_in_page"
      delete 'log_out', to: "kings_yangon_users#log_out"
    end
  end

  resources :page, only: [] do 
    collection do 
      get 'landing', to: 'page#landing'
    end
  end


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  
  resources :users, only: [:index, :show, :new, :edit, :update, :destroy] do
    collection do
      post '/create', to: 'users#create'
    end
  end
  # resources :users, only: [:index, :show]
  resources :contacts, except: [:new, :create]

  resources :blogs do 
    collection do 
      get '/filter_by_date', to: "blogs#filter_by_date"
    end
  end

  resources :categories
  resources :testimonials

  authenticated :user, ->(user) {user.management?} do
    root to: 'brand_categories#index', as: :management_root
  end

  authenticated :user do
    root to: 'blogs#index', as: :authenticated_root
  end

  authenticated :kings_yangon_user do 
    root to: 'page#landing', as: :landing_page
  end

  unauthenticated do
    devise_scope :user do
      root to: 'page#welcome'
    end
  end

  namespace :api do 
    namespace :v1 do 
      resources :blogs, only: [:index, :show] do 
        member do 
          get 'blogs_filter_category', to: 'blogs#blogs_filter_category'
          post :increment_view_count
        end
      end
      resources :contacts
    end
  end
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
  has_one_attached :image

  paginates_per 4 

  validates :name, presence: true, length: { maximum: 50 }
  validates :speech, presence: true
  validates :current_year_group, presence: true, length: {maximum: 100}
  validates :batch_year, presence: true
  private 
  # def batch_year_cannot_be_two_year_future
  #   if batch_year.present? && batch_year > Date.current.year + 2
  #     errors.add(:batch_year, ' cannot be two years into the future')
  #   end
  # end
  
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  load_and_authorize_resource
  before_action :set_testimonial, only: %i[ show edit update destroy ]
  # before_action :check_admin_access
  # GET /testimonials or /testimonials.json
  def index
    unless params[:query]
        @testimonials = Testimonial.all.order(:name).page(params[:page]).per(4)
        respond_to do |format|
          format.html 
          format.json {render json: {data: @testimonials} }
        end
    else 
      @testimonials = Testimonial.where("name LIKE ?", "%#{params[:query]}%").order(:name).page(params[:page]).per(4)
      respond_to do |format| 
        format.html 
      end
    end
  end

  # GET /testimonials/1 or /testimonials/1.json
  def show
  end

  # GET /testimonials/new
  def new
    @testimonial = Testimonial.new
  end

  # GET /testimonials/1/edit
  def edit
  end

  # POST /testimonials or /testimonials.json
  def create
    @testimonial = Testimonial.new(testimonial_params)

    respond_to do |format|
      if @testimonial.save
        format.html { redirect_to testimonials_path, notice: "Testimonial was successfully created." }
        format.json { render :show, status: :created, location: @testimonial }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /testimonials/1 or /testimonials/1.json
  def update
    puts testimonial_params
    respond_to do |format|
      if @testimonial.update(testimonial_params)
        format.html { redirect_to testimonials_path, notice: "Testimonial was successfully updated." }
        format.json { render :show, status: :ok, location: @testimonial }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @testimonial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonials/1 or /testimonials/1.json
  def destroy
    @testimonial.destroy!

    respond_to do |format|
      format.html { redirect_to testimonials_url, notice: "Testimonial was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_testimonial
      @testimonial = Testimonial.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def testimonial_params
      params.require(:testimonial).permit(:name, :speech, :image, :batch_year, :current_year_group)
    end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<%= render 'shared/back_button' %>
<%= render 'layouts/auth_layout' do %>
    <% if @testimonial.persisted?%>
      <%= render 'shared/form_title', locals:{title: 'Update Testimonial' }%>
    <% else %>
        <%= render 'shared/form_title', locals:{title: 'Create Testimonial' }%>
    <% end %>
    <div class="p-3 form-container">
        <%= form_with(model: testimonial) do |form| %>

        <div class="mb-3">
          <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :name, record: testimonial} %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

        <div class="mb-3">
          <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :speech, record: testimonial}%>
          <%= form.text_area :speech, class: 'form-control', style:"min-height: 250px" %>
        </div>

        <div class="mb-3">
          <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :batch_year, record: testimonial}%>
          <%= form.select :batch_year, (2010..Date.current.year).to_a, { prompt: "Select Batch Year" }, { class: 'form-select', selected: testimonial.batch_year.to_i } %>
        </div>

        <div class="mb-3">
          <%= render partial: 'shared/label_with_errors', locals: {form: form, field_name: :current_year_group, record: testimonial}%>
          <%= form.text_field :current_year_group, class: 'form-control' %>
        </div>

        <div class="mb-4">
          <% if testimonial.image.attached? %>
            <%= form.hidden_field :image, value: testimonial.image.signed_id %>
          <% end %>
          <%= form.label :image, style: "display: block", class: 'form-label' %>
          <%= form.file_field :image %>
        </div>

        <div class="mt-3">
          <% unless @testimonial.persisted?%>
              <%= form.submit "Create", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% else %>
              <%= form.submit "Update", class: 'btn btn-primary w-100 text-center fw-semibold ' %>
          <% end %>
        </div>
      <% end %>
    </div>
<% end %>

app/views/testimonials/_table.html.erb
<table class="table align-middle mb-0 bg-white">
  <thead class="bg-light">
    <tr>
      <th>Name</th>
      <th>Speech</th>
      <th>Batch Year</th>
      <th>Year Group</th>
       <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% if @testimonials.empty? %>
    <%= render 'shared/no_data_table'%>
  <% else %>
    <% @testimonials&.each do |testimonial| %>
            <tr>
                <td>
                    <div class="d-flex align-items-center">
                    <% if testimonial.image.present? %>
                        <%= image_tag testimonial.image, alt: 'testimonial', width: 45, height: 45, class: 'rounded-circle'%>
                    <% end %>
                    <div class="ms-3">
                        <p class="fw-bold mb-1"><%= testimonial.name %></p>
                    </div>
                    </div>
                </td>
                <td>
            <p class="text-truncate fw-normal mb-1 table-title" ><%= testimonial.speech %></p>
                </td>
                <td>
                    <span class="badge badge-success rounded-pill d-inline"><%= testimonial.batch_year  %></span>
                </td>
                <td><%= testimonial.current_year_group || '' %></td>
                <td class="">
                    <%= link_to testimonial_path(testimonial) do  %>
                        <i class="bi bi-eye-fill" style="font-size: 1.2rem"></i>           
                    <% end %>
                <% if current_user.admin? %>
                        <%= link_to 'Edit', edit_testimonial_path(id: testimonial.id), class: 'btn btn-link btn-sm btn-rounded' %>
                        <%#= link_to 'Create', new_user_path, class: ' btn btn-link btn-sm btn-rouned' %>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" id="testimonialModelLabel<%= testimonial.id %>" data-bs-target="#testimonialModel<%= testimonial.id %>">
                            Delete
                        </button>
                        <!-- Modal -->
                    <div class="modal fade" id="testimonialModel<%= testimonial.id %>" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="testimonialModelLabel<%= testimonial.id %>" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body text-center fw-semibold">
                                Are you sure you want to delete this testimonial ? 
                            </div>
                            <div class="modal-footer">
                                <%= button_to "Delete", testimonial_path(testimonial), { class: 'btn btn-danger', method: :delete } %>
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                            </div>
                        </div>
                    </div>
                <% end %>

                </td>
            </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<%= render 'shared/paginate_footer', locals: {items: @testimonials} %>


app/views/testimonials/_testimonial.html.erb
<div id="<%= dom_id testimonial %>">
  <p>
    <strong>Name:</strong>
    <%= testimonial.name %>
  </p>

  <p>
    <strong>Speech:</strong>
    <%= testimonial.speech %>
  </p>
  <% if @testimonial && @testimonial&.image.attached?  %>
    <p>
      <strong>Image:</strong>
      <%= image_tag @testimonial.image, alt: @testimonial.name, size: "300x200" %>
    </p>
  <% end %>
</div>

app/views/testimonials/edit.html.erb
<%= render "form", testimonial: @testimonial %>

app/views/testimonials/index.html.erb
<%= render 'shared/back_button' %>
<%= render 'shared/create_button', locals: {link: new_testimonial_path } %>
<%= render 'shared/search_form', locals: {link: testimonials_path, title: 'Testimonials', current_data: @testimonials } %>
<%= render 'table' %>

app/views/testimonials/new.html.erb
<%= render "form", testimonial: @testimonial %>

app/views/testimonials/show.html.erb
<%= render @testimonial %>